"""
notification.py

Notification model.

Author: Andrew Kyalo
Project: Andy Scanner
"""

from datetime import datetime
from enum import Enum


class NotificationType(Enum):
    """
    Supported notification types.
    """

    SIGNAL = "SIGNAL"
    SYSTEM = "SYSTEM"
    WARNING = "WARNING"
    ERROR = "ERROR"
    INFO = "INFO"


class NotificationPriority(Enum):
    """
    Notification priority levels.
    """

    LOW = "LOW"
    NORMAL = "NORMAL"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class Notification:
    """
    Represents a notification generated by Andy Scanner.
    """

    def __init__(
        self,
        title,
        message,
        notification_type=NotificationType.INFO,
        priority=NotificationPriority.NORMAL,
        channel="SYSTEM",
        metadata=None,
    ):

        self.id = datetime.now().strftime("%Y%m%d%H%M%S%f")

        self.title = str(title)

        self.message = str(message)

        self.notification_type = notification_type

        self.priority = priority

        self.channel = channel

        self.metadata = metadata or {}

        self.created_at = datetime.now()

        self.sent = False

        self.sent_at = None

    # ==================================================
    # Status
    # ==================================================

    def mark_sent(self):

        self.sent = True

        self.sent_at = datetime.now()

    # ==================================================
    # Serialization
    # ==================================================

    def to_dict(self):

        return {

            "id": self.id,

            "title": self.title,

            "message": self.message,

            "type": self.notification_type.value,

            "priority": self.priority.value,

            "channel": self.channel,

            "created_at": self.created_at,

            "sent": self.sent,

            "sent_at": self.sent_at,

            "metadata": dict(self.metadata),
        }

    # ==================================================
    # Summary
    # ==================================================

    def summary(self):

        return {

            "id": self.id,

            "title": self.title,

            "type": self.notification_type.value,

            "priority": self.priority.value,

            "channel": self.channel,

            "sent": self.sent,
        }

    # ==================================================
    # String Representation
    # ==================================================

    def __str__(self):

        return (
            f"[{self.priority.value}] "
            f"{self.notification_type.value} "
            f"{self.title}"
        )