"""
database_stage.py

Database Pipeline Stage.

Author: Andrew Kyalo
Project: Andy Scanner
"""

from datetime import datetime

from backend.pipeline.pipeline_stage import PipelineStage
from database.database_manager import DatabaseManager


class DatabaseStage(PipelineStage):
    """
    Saves completed scanner results into the database.

    Persists:
        - market
        - timeframe
        - trend
        - signal
        - confidence
        - trade setup
        - entry
        - stop loss
        - take profit
        - risk/reward
        - structural validity
        - risk validation
    """

    def __init__(self):

        super().__init__("Database Stage")

    # ==========================================================
    # Execute
    # ==========================================================

    def execute(self, context):
        """
        Persist the current pipeline result.

        TradeSetup generated by TradeSetupStage is passed
        directly to DatabaseManager.
        """

        scan_time = datetime.now()

        with DatabaseManager() as database:

            exists = database.scan_exists(
                context.market,
                context.timeframe,
                scan_time.strftime(
                    "%Y-%m-%d %H:%M:%S"
                ),
            )

            # ==================================================
            # Duplicate
            # ==================================================

            if exists:

                context.set_metadata(
                    "database",
                    "DUPLICATE",
                )

                context.set_metadata(
                    "trade_setup_persisted",
                    False,
                )

                return context

            # ==================================================
            # Signal
            # ==================================================

            database.save_signal(
                context.signal
            )

            # ==================================================
            # Analysis
            # ==================================================

            trend = None

            if context.analysis is not None:

                trend = context.analysis.trend

            # ==================================================
            # Trade Setup
            # ==================================================

            trade_setup = context.trade_setup

            # ==================================================
            # Save Scan
            # ==================================================

            database.save_scan(
                market=context.market,
                timeframe=context.timeframe,
                trend=trend,
                signal=context.signal.direction,
                confidence=context.signal.confidence,
                trade_setup=trade_setup,
            )

            # ==================================================
            # Database Metadata
            # ==================================================

            context.set_metadata(
                "database",
                "SAVED",
            )

            context.set_metadata(
                "trade_setup_persisted",
                trade_setup is not None,
            )

            context.set_metadata(
                "trade_setup_valid",
                (
                    trade_setup.valid
                    if trade_setup is not None
                    else False
                ),
            )

            # ==================================================
            # Risk Validation Metadata
            # ==================================================

            validation = getattr(
                context,
                "trade_setup_validation",
                None,
            )

            context.set_metadata(
                "risk_validation_persisted",
                validation is not None,
            )

            if validation is not None:

                context.set_metadata(
                    "risk_validation",
                    (
                        "ACCEPTED"
                        if validation.valid
                        else "REJECTED"
                    ),
                )

                context.set_metadata(
                    "risk_validation_reason",
                    validation.reason,
                )

                context.set_metadata(
                    "risk_validation_rr",
                    validation.risk_reward,
                )

            else:

                context.set_metadata(
                    "risk_validation",
                    "NOT_AVAILABLE",
                )

                context.set_metadata(
                    "risk_validation_reason",
                    None,
                )

                context.set_metadata(
                    "risk_validation_rr",
                    None,
                )

            return context
