"""
database_stage.py

Database Pipeline Stage.

Author: Andrew Kyalo
Project: Andy Scanner
"""

from datetime import datetime

from backend.pipeline.pipeline_stage import PipelineStage
from database.database_manager import DatabaseManager


class DatabaseStage(PipelineStage):
    """
    Saves completed scanner results into the database.

    Persists:
        - market
        - timeframe
        - trend
        - signal
        - confidence
        - trade setup
        - entry
        - stop loss
        - take profit
        - risk/reward
        - setup validity
    """

    def __init__(self):

        super().__init__("Database Stage")

    # ==========================================================
    # Execute
    # ==========================================================

    def execute(self, context):
        """
        Persist the current pipeline result.

        The TradeSetup generated by TradeSetupStage is passed
        directly to DatabaseManager for persistence.
        """

        scan_time = datetime.now()

        with DatabaseManager() as database:

            exists = database.scan_exists(
                context.market,
                context.timeframe,
                scan_time.strftime(
                    "%Y-%m-%d %H:%M:%S"
                ),
            )

            if not exists:

                # ==============================================
                # SAVE SIGNAL
                # ==============================================

                database.save_signal(
                    context.signal
                )

                # ==============================================
                # SAVE SCAN + TRADE SETUP
                # ==============================================

                database.save_scan(
                    market=context.market,
                    timeframe=context.timeframe,
                    trend=context.trend,
                    signal=context.signal.direction,
                    confidence=context.signal.confidence,
                    trade_setup=context.trade_setup,
                )

                context.set_metadata(
                    "database",
                    "SAVED",
                )

                # ==============================================
                # TRADE SETUP DATABASE STATUS
                # ==============================================

                if context.trade_setup is not None:

                    context.set_metadata(
                        "trade_setup_persisted",
                        True,
                    )

                    context.set_metadata(
                        "trade_setup_valid",
                        context.trade_setup.valid,
                    )

                else:

                    context.set_metadata(
                        "trade_setup_persisted",
                        False,
                    )

            else:

                context.set_metadata(
                    "database",
                    "DUPLICATE",
                )

                context.set_metadata(
                    "trade_setup_persisted",
                    False,
                )

        return context